#!/bin/bash

runNum=999

for ((FL=2;FL<5;FL++)); do
    for ((FG=0;FG<2;FG++)); do
    	for ((d=1;d<3;d++));do
	    
	    ./EvtBuilder $runNum $FL $FG $d 0.5 &> log_${runNum}_${FL}_${FG}_${d} &

done



done


done