#!/bin/bash

NO_ARGS=0;

if [ $# -eq "$NO_ARGS" ] || [ $# -eq 1 ]  # Script invoked with no command-line args?
then
  echo "Usage: ./`basename $0` -r run_number options(d)"
  exit 1          # Exit and explain usage, if no argument(s) given.
fi  
# Usage: scriptname -options
# Note: dash (-) necessary

doDDASdump=0;
runNum=0;
build=0;

while getopts ":dr:b" Option
do
  case $Option in
    d     ) doDDASdump=1;;
    r     ) runNum=$OPTARG;;
    b     ) build=1;;
    *     ) echo "Unimplemented option chosen.";;   # DEFAULT
  esac
done


shift $(($OPTIND - 1))


loc=`pwd`
path='/mnt/daqtesting/lenda/experiment/run'${runNum}
path2='/mnt/daqtesting/lenda/rootfiles/'

cd $path
num=`ls | wc -l`

if [ $doDDASdump -eq 1 ]; then 
    cd ~/neutron/DDAS/ddasdumper
    
    
    for ((i=0;i<$num;i++)); do
	
	if [ $i -lt 10 ]; then
	    ./ddasdumper --source=file:///mnt/daqtesting/lenda/experiment/run${runNum}/run-0${runNum}-0${i}.evt --fileout=/mnt/daqtesting/lenda/rootfiles/run-0${runNum}-0${i}.root
	fi
	
	if [ $i -ge 10 ]; then
	    ./ddasdumper --source=file:///mnt/daqtesting/lenda/experiment/run${runNum}/run-0${runNum}-${i}.evt --fileout=/mnt/daqtesting/lenda/rootfiles/run-0${runNum}-${i}.root
	fi
    done
fi
    

##script is run from sam_analysis directory
cd $loc

##check to see if all the files are in sam_analysis
allGood=1;

for ((i=0;i<$num;i++)); do 
    if [ $i -lt 10 ]; then
	file=run-0${runNum}-0${i}.root;
	if [ ! -f $file ];then
	    allGood=0;
	    break;
	fi
    fi
    
    if [ $i -ge 10 ]; then
	file=run-0${runNum}-${i}.root;
	if [ ! -f $file ];then
	    allGood=0;
	    break;
	fi
    fi

done
#############


if [ $allGood -eq 1 ]; then
    echo "All the root files have been linked to sam_analysis"
elif [ $allGood -ne 1 ]; then 
    echo "Need to make links for the files"

    for ((i=0;i<$num;i++)); do
	if [ $i -lt 10 ]; then
	    file=run-0${runNum}-0${i}.root;
        elif [ $i -ge 10 ];then
	    file=run-0${runNum}-${i}.root;
	fi

	if [ -f ../rootfiles/${file} ]  && [ ! -f ./${file} ]; then

	    echo "This file needs a link: " $file
	    echo "Linking..."
	    ln -s ../rootfiles/${file} ./${file}
	fi
    done
fi


if [ $build -eq 1 ]; then

    ./EvtBuilder $runNum numFiles:$num timingMode:internalCFD
fi

echo Done | mail soam5515@yahoo.com
